name: Update rabbitmq-queue-management
on:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  updateRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest rabbitmq-queue-management release
        id: mq
        env:
          VERSIONS_YAML: versions.yaml
        run: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq

          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/gessnerfl/rabbitmq-queue-management/releases/latest | jq -r ".tag_name")
          echo ::set-output name=release_sha::$(curl -sL https://api.github.com/repos/gessnerfl/rabbitmq-queue-management/releases/latest | jq -r ".target_commitish")
          echo ::set-output name=current_tag::$(yq ".rabbitmq_queue_management" $VERSIONS_YAML)
      - name: Update versions file
        if: steps.mq.outputs.current_tag != steps.mq.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.mq.outputs.release_tag }}
          RELEASE_SHA: ${{ steps.mq.outputs.release_sha }}
          VERSIONS_YAML: versions.yaml
        run: |
          yq -i ".image.version = strenv(RELEASE_TAG)" $VERSIONS_YAML
          yq -i ".rabbitmq_queue_management = strenv(RELEASE_TAG)" $VERSIONS_YAML
          yq -i ".rabbitmq_queue_management_sha = strenv(RELEASE_SHA)" $VERSIONS_YAML
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update to ${{ steps.mq.outputs.release_tag }}
          title: Update to ${{ steps.mq.outputs.release_tag }}
          body: |
            Updates [rabbitmq-queue-management][1] to ${{ steps.mq.outputs.release_tag }}

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/gessnerfl/rabbitmq-queue-management
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: rabbitmq-queue-management-updates